usrin = input()
usrinList = usrin.split(' ')
valA = int(usrinList[0])
valB = int(usrinList[1])
valC = int(usrinList[2])
print((valA+valB)%valC)
print(((valA%valC)+(valB%valC))%valC)
print((valA*valB)%valC)
print((valA%valC)*(valB%valC)%valC)